import { Metadata } from "next";
import RootLayout from "./RootLayout"; // Your existing RootLayout component

// Server-side metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayout>{children}</RootLayout>;
}
